In [18]:
import pandas as pd
import numpy as np

from keras.models import load_model

In [7]:
from keras.models import Sequential

In [11]:
from keras.layers.embeddings import Embedding

In [12]:
from keras.layers import (
    LSTM,
    Bidirectional,
    CuDNNLSTM,
    Dense,
    Dropout,
    RepeatVector,
    TimeDistributed,
)

In [13]:
num_cells = 100
drop_out_rate = 0.2

top_words = 3
embedding_vector_length = 1
max_length = 204

In [68]:
model = Sequential()

model.add(
    Embedding(top_words, embedding_vector_length, input_length=max_length)
)
model.add(Bidirectional(LSTM(num_cells)))

model.add(Dropout(rate=drop_out_rate))
model.add(Dense(1, activation="sigmoid"))

model.load_weights('hawk_output/output_padded/final_lstm_model_1.h5')

In [69]:
input_lenght = 204

In [70]:
test_input  = np.array([2, 2, 2, 2, 2, 2, 2, 2, 2] + [0 for _ in range(input_lenght - 9)] )
test_input = test_input.reshape((1, input_lenght))

In [71]:
output = model.predict(test_input)

In [72]:
output

array([[0.20495209]], dtype=float32)

**Check your data to make sure there is no NaN in it**

In [73]:
inputs = pd.read_csv("data/padded_inputs_classification.csv", index_col=0)

//anaconda3/envs/rnn/lib/python3.6/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [74]:
isit = np.isnan(inputs.values)

In [75]:
sum(isit)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [62]:
outputs = pd.read_csv("data/classification_output.csv", index_col=0)

//anaconda3/envs/rnn/lib/python3.6/site-packages/numpy/lib/arraysetops.py:568: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [63]:
isit = np.isnan(outputs.values)

In [64]:
sum(isit)

array([0])

**Check the gradients and the weights to make sure there is no NaN.**

In [76]:
weights = []
for layer in model.layers:
    weights.append(layer.get_weights())

In [77]:
sum(np.isnan(weights[0])), sum(np.isnan(weights[1][0])), sum(np.isnan(weights[1][1]))

(array([[0],
        [0],
        [0]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [78]:
sum(np.isnan(weights[-1][0])), sum(np.isnan(weights[-1][1]))

(array([0]), 0)

**To make sure everything's right, check the predictions of your network so that your network is not making some constant, or repetitive predictions.**

In [79]:
input_lenght = 204
test_lenght = 100

In [82]:
test_input  = np.array([2 for _ in range(test_lenght)] + [0 for _ in range(input_lenght - test_lenght)] )
test_input = test_input.reshape((1, input_lenght))

In [83]:
model.predict(test_input)

array([[0.35501415]], dtype=float32)

In [84]:
test_input  = np.array([1 for _ in range(test_lenght)] + [0 for _ in range(input_lenght - test_lenght)] )
test_input = test_input.reshape((1, input_lenght))

In [85]:
model.predict(test_input)

array([[0.68726444]], dtype=float32)

**The values of the weights**

In [86]:
model.layers[0].get_weights()

[array([[-0.88638216],
        [ 2.47772   ],
        [-1.9246606 ]], dtype=float32)]